[package]
name = "pdftract-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "WASM bindings for pdftract's vector-text extraction (browser demo)"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pdftract-core = { path = "../pdftract-core", version = "0.1.0", default-features = false, features = [
    "serde",
    "decrypt",
    "quick-xml",
] }
serde_json = "1.0"
wasm-bindgen = "0.2"
